# Generated by Django 3.2.4 on 2021-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Empid', models.AutoField(primary_key=True, serialize=False)),
                ('Empname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.IntegerField()),
                ('Password', models.CharField(max_length=30)),
                ('RePassword', models.CharField(max_length=30)),
            ],
        ),
    ]
