# Generated by Django 3.2.4 on 2021-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0006_auto_20210713_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Email',
            field=models.EmailField(max_length=100, verbose_name='Email (Your Username)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Pune', 'rachi'), ('Kanpur', 'Kanpur'), ('Ahmedabad', 'Ahmedabad'), ('Gujrat', 'Gujrat'), ('Dosa', 'Dosa'), ('Jaipur', 'Jaipur'), ('Bikaner', 'Bikaner'), ('Agra', 'Agra'), ('Ranchi', 'ranchi'), ('Bhilwara', 'Bhilwara'), ('Dehradun', 'Dehradun'), ('jodhpur', 'Jodhpur'), ('Chandigarh', 'Chandigarh'), ('Alwar', 'Alwar'), ('Bagru', 'Bagru'), ('Mumbai', 'Mumbai'), ('Vishakapatnam', 'Vishakapatnam'), ('Ajmer', 'Ajmer'), ('Delhi', 'Delhi'), ('Bareilly', 'Bareilly'), ('Bangalore', 'Banglore')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Password',
            field=models.CharField(max_length=30),
        ),
    ]
