# Generated by Django 3.2.4 on 2021-07-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0007_auto_20210713_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Pune', 'rachi'), ('Dosa', 'Dosa'), ('Kanpur', 'Kanpur'), ('Dehradun', 'Dehradun'), ('Vishakapatnam', 'Vishakapatnam'), ('Mumbai', 'Mumbai'), ('Ahmedabad', 'Ahmedabad'), ('Bareilly', 'Bareilly'), ('Alwar', 'Alwar'), ('Ajmer', 'Ajmer'), ('Chandigarh', 'Chandigarh'), ('jodhpur', 'Jodhpur'), ('Gujrat', 'Gujrat'), ('Ranchi', 'ranchi'), ('Bagru', 'Bagru'), ('Bikaner', 'Bikaner'), ('Delhi', 'Delhi'), ('Bangalore', 'Banglore'), ('Bhilwara', 'Bhilwara'), ('Agra', 'Agra'), ('Jaipur', 'Jaipur')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
