# Generated by Django 3.2.4 on 2021-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0008_auto_20210713_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Gender',
            field=models.BooleanField(choices=[('Others', 'Others'), ('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Ranchi', 'ranchi'), ('Vishakapatnam', 'Vishakapatnam'), ('Pune', 'rachi'), ('jodhpur', 'Jodhpur'), ('Bikaner', 'Bikaner'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh'), ('Agra', 'Agra'), ('Dehradun', 'Dehradun'), ('Bangalore', 'Banglore'), ('Bagru', 'Bagru'), ('Bareilly', 'Bareilly'), ('Jaipur', 'Jaipur'), ('Dosa', 'Dosa'), ('Gujrat', 'Gujrat'), ('Bhilwara', 'Bhilwara'), ('Ajmer', 'Ajmer'), ('Alwar', 'Alwar'), ('Ahmedabad', 'Ahmedabad'), ('Kanpur', 'Kanpur')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
