# Generated by Django 3.2.4 on 2021-07-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0009_auto_20210713_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Others', 'Others'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Jaipur', 'Jaipur'), ('Agra', 'Agra'), ('Kanpur', 'Kanpur'), ('Alwar', 'Alwar'), ('Bhilwara', 'Bhilwara'), ('Dehradun', 'Dehradun'), ('Ranchi', 'ranchi'), ('Bagru', 'Bagru'), ('Bareilly', 'Bareilly'), ('Chandigarh', 'Chandigarh'), ('Vishakapatnam', 'Vishakapatnam'), ('Mumbai', 'Mumbai'), ('Ahmedabad', 'Ahmedabad'), ('Ajmer', 'Ajmer'), ('Gujrat', 'Gujrat'), ('Bangalore', 'Banglore'), ('Bikaner', 'Bikaner'), ('jodhpur', 'Jodhpur'), ('Delhi', 'Delhi'), ('Pune', 'rachi'), ('Dosa', 'Dosa')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
