# Generated by Django 3.2.4 on 2021-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0011_auto_20210713_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Ranchi', 'ranchi'), ('Ajmer', 'Ajmer'), ('Bhilwara', 'Bhilwara'), ('Bareilly', 'Bareilly'), ('jodhpur', 'Jodhpur'), ('Pune', 'rachi'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Gujrat', 'Gujrat'), ('Ahmedabad', 'Ahmedabad'), ('Mumbai', 'Mumbai'), ('Bikaner', 'Bikaner'), ('Vishakapatnam', 'Vishakapatnam'), ('Jaipur', 'Jaipur'), ('Dosa', 'Dosa'), ('Bagru', 'Bagru'), ('Agra', 'Agra'), ('Kanpur', 'Kanpur'), ('Bangalore', 'Banglore'), ('Dehradun', 'Dehradun'), ('Alwar', 'Alwar')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
