# Generated by Django 3.2.4 on 2021-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0012_alter_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Bareilly', 'Bareilly'), ('Mumbai', 'Mumbai'), ('Agra', 'Agra'), ('Delhi', 'Delhi'), ('Dosa', 'Dosa'), ('Pune', 'rachi'), ('Bangalore', 'Banglore'), ('Jaipur', 'Jaipur'), ('Ahmedabad', 'Ahmedabad'), ('Alwar', 'Alwar'), ('Chandigarh', 'Chandigarh'), ('Ranchi', 'ranchi'), ('Bikaner', 'Bikaner'), ('Ajmer', 'Ajmer'), ('Bagru', 'Bagru'), ('jodhpur', 'Jodhpur'), ('Dehradun', 'Dehradun'), ('Gujrat', 'Gujrat'), ('Kanpur', 'Kanpur'), ('Bhilwara', 'Bhilwara'), ('Vishakapatnam', 'Vishakapatnam')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
