# Generated by Django 3.2.4 on 2021-07-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0013_auto_20210713_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Agra', 'Agra'), ('Bareilly', 'Bareilly'), ('Bhilwara', 'Bhilwara'), ('Gujrat', 'Gujrat'), ('Ranchi', 'ranchi'), ('Jaipur', 'Jaipur'), ('Mumbai', 'Mumbai'), ('Pune', 'rachi'), ('Alwar', 'Alwar'), ('Dehradun', 'Dehradun'), ('Ajmer', 'Ajmer'), ('Bikaner', 'Bikaner'), ('Dosa', 'Dosa'), ('Ahmedabad', 'Ahmedabad'), ('Bangalore', 'Banglore'), ('Bagru', 'Bagru'), ('jodhpur', 'Jodhpur'), ('Vishakapatnam', 'Vishakapatnam'), ('Kanpur', 'Kanpur'), ('Delhi', 'Delhi'), ('Chandigarh', 'Chandigarh')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
