# Generated by Django 3.2.4 on 2021-07-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0014_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Ajmer', 'Ajmer'), ('Vishakapatnam', 'Vishakapatnam'), ('Bikaner', 'Bikaner'), ('Gujrat', 'Gujrat'), ('Kanpur', 'Kanpur'), ('Pune', 'rachi'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Dehradun', 'Dehradun'), ('Chandigarh', 'Chandigarh'), ('Agra', 'Agra'), ('Bagru', 'Bagru'), ('Alwar', 'Alwar'), ('Ranchi', 'ranchi'), ('Dosa', 'Dosa'), ('Bareilly', 'Bareilly'), ('jodhpur', 'Jodhpur'), ('Ahmedabad', 'Ahmedabad'), ('Bhilwara', 'Bhilwara'), ('Bangalore', 'Banglore'), ('Jaipur', 'Jaipur')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
