# Generated by Django 3.2.4 on 2021-07-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0016_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Ajmer', 'Ajmer'), ('jodhpur', 'Jodhpur'), ('Alwar', 'Alwar'), ('Bhilwara', 'Bhilwara'), ('Bikaner', 'Bikaner'), ('Gujrat', 'Gujrat'), ('Jaipur', 'Jaipur'), ('Bagru', 'Bagru'), ('Chandigarh', 'Chandigarh'), ('Agra', 'Agra'), ('Kanpur', 'Kanpur'), ('Vishakapatnam', 'Vishakapatnam'), ('Delhi', 'Delhi'), ('Mumbai', 'Mumbai'), ('Ranchi', 'ranchi'), ('Bareilly', 'Bareilly'), ('Dosa', 'Dosa'), ('Dehradun', 'Dehradun'), ('Ahmedabad', 'Ahmedabad'), ('Pune', 'rachi'), ('Bangalore', 'Banglore')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
