# Generated by Django 3.2.4 on 2021-07-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0017_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Dosa', 'Dosa'), ('Gujrat', 'Gujrat'), ('jodhpur', 'Jodhpur'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Ajmer', 'Ajmer'), ('Agra', 'Agra'), ('Jaipur', 'Jaipur'), ('Bhilwara', 'Bhilwara'), ('Pune', 'rachi'), ('Bikaner', 'Bikaner'), ('Bangalore', 'Banglore'), ('Ranchi', 'ranchi'), ('Mumbai', 'Mumbai'), ('Vishakapatnam', 'Vishakapatnam'), ('Bareilly', 'Bareilly'), ('Dehradun', 'Dehradun'), ('Bagru', 'Bagru'), ('Ahmedabad', 'Ahmedabad'), ('Kanpur', 'Kanpur'), ('Alwar', 'Alwar')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
