# Generated by Django 3.2.4 on 2021-07-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0019_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Dosa', 'Dosa'), ('Pune', 'rachi'), ('Bagru', 'Bagru'), ('Vishakapatnam', 'Vishakapatnam'), ('Gujrat', 'Gujrat'), ('Mumbai', 'Mumbai'), ('Bareilly', 'Bareilly'), ('Ranchi', 'ranchi'), ('Alwar', 'Alwar'), ('jodhpur', 'Jodhpur'), ('Ahmedabad', 'Ahmedabad'), ('Bangalore', 'Banglore'), ('Bhilwara', 'Bhilwara'), ('Bikaner', 'Bikaner'), ('Dehradun', 'Dehradun'), ('Jaipur', 'Jaipur'), ('Chandigarh', 'Chandigarh'), ('Kanpur', 'Kanpur'), ('Delhi', 'Delhi'), ('Ajmer', 'Ajmer'), ('Agra', 'Agra')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
