# Generated by Django 3.2.4 on 2021-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0020_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Ajmer', 'Ajmer'), ('Pune', 'rachi'), ('Bareilly', 'Bareilly'), ('Delhi', 'Delhi'), ('Vishakapatnam', 'Vishakapatnam'), ('Ahmedabad', 'Ahmedabad'), ('Dehradun', 'Dehradun'), ('Agra', 'Agra'), ('Kanpur', 'Kanpur'), ('jodhpur', 'Jodhpur'), ('Bikaner', 'Bikaner'), ('Gujrat', 'Gujrat'), ('Dosa', 'Dosa'), ('Jaipur', 'Jaipur'), ('Bhilwara', 'Bhilwara'), ('Bangalore', 'Banglore'), ('Bagru', 'Bagru'), ('Alwar', 'Alwar'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Ranchi', 'ranchi')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
