# Generated by Django 3.2.4 on 2021-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0022_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Ajmer', 'Ajmer'), ('Bagru', 'Bagru'), ('Mumbai', 'Mumbai'), ('Agra', 'Agra'), ('Dehradun', 'Dehradun'), ('Kanpur', 'Kanpur'), ('Delhi', 'Delhi'), ('Dosa', 'Dosa'), ('Bangalore', 'Banglore'), ('Bareilly', 'Bareilly'), ('Ahmedabad', 'Ahmedabad'), ('jodhpur', 'Jodhpur'), ('Bikaner', 'Bikaner'), ('Pune', 'rachi'), ('Jaipur', 'Jaipur'), ('Ranchi', 'ranchi'), ('Gujrat', 'Gujrat'), ('Bhilwara', 'Bhilwara'), ('Alwar', 'Alwar'), ('Vishakapatnam', 'Vishakapatnam'), ('Chandigarh', 'Chandigarh')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
