# Generated by Django 3.2.4 on 2021-07-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0023_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Pune', 'rachi'), ('Bagru', 'Bagru'), ('Agra', 'Agra'), ('Bhilwara', 'Bhilwara'), ('Delhi', 'Delhi'), ('Bikaner', 'Bikaner'), ('Vishakapatnam', 'Vishakapatnam'), ('Jaipur', 'Jaipur'), ('Gujrat', 'Gujrat'), ('Kanpur', 'Kanpur'), ('Bareilly', 'Bareilly'), ('Alwar', 'Alwar'), ('Ajmer', 'Ajmer'), ('Dehradun', 'Dehradun'), ('Ranchi', 'ranchi'), ('Bangalore', 'Banglore'), ('Dosa', 'Dosa'), ('Chandigarh', 'Chandigarh'), ('Ahmedabad', 'Ahmedabad'), ('Mumbai', 'Mumbai'), ('jodhpur', 'Jodhpur')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
