# Generated by Django 3.2.7 on 2021-10-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0024_alter_employee_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Location',
            field=models.CharField(choices=[('Vishakapatnam', 'Vishakapatnam'), ('Agra', 'Agra'), ('Alwar', 'Alwar'), ('jodhpur', 'Jodhpur'), ('Dehradun', 'Dehradun'), ('Bangalore', 'Banglore'), ('Bareilly', 'Bareilly'), ('Bikaner', 'Bikaner'), ('Ajmer', 'Ajmer'), ('Bagru', 'Bagru'), ('Gujrat', 'Gujrat'), ('Ahmedabad', 'Ahmedabad'), ('Jaipur', 'Jaipur'), ('Bhilwara', 'Bhilwara'), ('Mumbai', 'Mumbai'), ('Kanpur', 'Kanpur'), ('Ranchi', 'ranchi'), ('Chandigarh', 'Chandigarh'), ('Pune', 'rachi'), ('Delhi', 'Delhi'), ('Dosa', 'Dosa')], default='Delhi', max_length=50, verbose_name='CITY'),
        ),
    ]
